[meta]
  title = "Go Text-to-Speech Starter"
  description = "Get started using Deepgram's Text-to-Speech with this Go demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "text-to-speech"
  language = "go"
  tags = ["text-to-speech", "tts", "speech-synthesis", "go"]

[build]
  command = "go get"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `go run .` to get up and running."
